package ec.edu.uce.algoritmos.clases;

import static ec.edu.uce.algoritmos.clases.AdministrarElementos.adm;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 * PROYECTO: Dada una clase Persona y sus atributos realizamos tanto el
 * ingreso,editar,buscar e imprimir los elementos que se almacena en un arreglo
 * para proceder a buscar aplicando busqueda binaria, interpolacion y fibonacci.
 *
 * Clase con interfaz del logging para iniciar sesiòn en la aplicaciòn.
 *
 * FECHA:12-DIC-2016
 *
 * @author: 1725149502 David Morales 1312960444 Michael Ponce Cevallos
 * 1721468021 Estefania Portilla
 * @version 1.0.0
 */
public class Logging extends javax.swing.JFrame {

    /**
     * Constructor de la nueva forma Logging
     */
    public Logging() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Acceso");
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/star.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        msjError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(280, 330));
        setMinimumSize(new java.awt.Dimension(280, 330));
        setPreferredSize(new java.awt.Dimension(280, 330));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESO AL SISTEMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 36, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 91, -1, -1));

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setCaretColor(new java.awt.Color(255, 51, 51));
        user.setOpaque(false);
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 88, 77, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 138, -1, -1));

        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setCaretColor(new java.awt.Color(255, 51, 51));
        pass.setOpaque(false);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 135, 77, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        msjError.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(msjError, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 164, 163, 21));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/77506782d130c09bdd5bf91562a7f3d4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String usu1 = "michaelponce";
        String usu2 = "estefaniaportilla";
        String usu3 = "davidmorales";
        String usu = (user.getText() + pass.getText()).toLowerCase();

        // se compara el usuario y contraseña que sean correcta para acceder al menu principal. 
        if (usu.equals(usu1) || usu.equals(usu2) || usu.equals(usu3)) {
            adm.nuevo("1312960444", "Michael Ponce ", (byte) 20, new Date(7, 11, 1996), 200.0, "mfponce@uce.edu.ec");
            adm.nuevo("1725149502", "David Morales ", (byte) 21, new Date(9, 3, 1995), 205.0, "dmmoraless@uce.edu.ec");
            MenuPrincipal menu = new MenuPrincipal();
            this.dispose();
            menu.setVisible(true);

        } else {
            user.setText("");
            pass.setText("");
            msjError.setText("Ingrese unas credenciales válidas");

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel msjError;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
