package ec.edu.uce.algoritmos.clases;

/**
 * PROYECTO: Dada una clase Persona y sus atributos realizamos tanto el
 * ingreso,editar,buscar e imprimir los elementos que se almacena en un arreglo
 * para proceder a buscar aplicando busqueda binaria, interpolacion y fibonacci.
 * Clase con interfaz que muestra el menu principal
 *
 * FECHA:12-DIC-2016
 *
 * @author: 1725149502 David Morales 1312960444 Michael Ponce Cevallos
 * 1721468021 Estefania Portilla
 * @version 1.0.0
 */
public class MenuPrincipal extends javax.swing.JDialog {

    /**
     * Constructor de la nueva forma MenuPrincipal
     */
    public MenuPrincipal() {

        initComponents();
        setTitle("Menú");
        setLocationRelativeTo(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insElem = new javax.swing.JButton();
        editElem = new javax.swing.JButton();
        borrElem = new javax.swing.JButton();
        busElem = new javax.swing.JButton();
        imprElem = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(260, 290));
        setMinimumSize(new java.awt.Dimension(260, 290));
        setPreferredSize(new java.awt.Dimension(260, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insElem.setForeground(new java.awt.Color(255, 255, 255));
        insElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        insElem.setText("Insertar Elemento");
        insElem.setBorder(null);
        insElem.setBorderPainted(false);
        insElem.setContentAreaFilled(false);
        insElem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insElem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insElem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        insElem.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        insElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insElemActionPerformed(evt);
            }
        });
        getContentPane().add(insElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        editElem.setForeground(new java.awt.Color(255, 255, 255));
        editElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        editElem.setText("Editar Elemento");
        editElem.setBorder(null);
        editElem.setBorderPainted(false);
        editElem.setContentAreaFilled(false);
        editElem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editElem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editElem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        editElem.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        editElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editElemActionPerformed(evt);
            }
        });
        getContentPane().add(editElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        borrElem.setForeground(new java.awt.Color(255, 255, 255));
        borrElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        borrElem.setText("Borrar Elemento");
        borrElem.setBorder(null);
        borrElem.setBorderPainted(false);
        borrElem.setContentAreaFilled(false);
        borrElem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrElem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrElem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        borrElem.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        borrElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrElemActionPerformed(evt);
            }
        });
        getContentPane().add(borrElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        busElem.setForeground(new java.awt.Color(255, 255, 255));
        busElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        busElem.setText("Buscar Elemento");
        busElem.setBorder(null);
        busElem.setBorderPainted(false);
        busElem.setContentAreaFilled(false);
        busElem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busElem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        busElem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        busElem.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        busElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busElemActionPerformed(evt);
            }
        });
        getContentPane().add(busElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        imprElem.setForeground(new java.awt.Color(255, 255, 255));
        imprElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        imprElem.setText("Imprimir Elementos");
        imprElem.setBorder(null);
        imprElem.setBorderPainted(false);
        imprElem.setContentAreaFilled(false);
        imprElem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprElem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprElem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        imprElem.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        imprElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprElemActionPerformed(evt);
            }
        });
        getContentPane().add(imprElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b1.png"))); // NOI18N
        salir.setText("Salir");
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b3.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b2.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/77506782d130c09bdd5bf91562a7f3d4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insElemActionPerformed

        InsertarElemento ins = new InsertarElemento(null, rootPaneCheckingEnabled);
        ins.setVisible(true);

    }//GEN-LAST:event_insElemActionPerformed

    private void editElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editElemActionPerformed
     /*   EditarElemento edit = new EditarElemento(null, rootPaneCheckingEnabled);
        edit.setVisible(true);*/
    }//GEN-LAST:event_editElemActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void imprElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprElemActionPerformed

        VerDatos visualizar = new VerDatos(null, rootPaneCheckingEnabled);
        visualizar.setVisible(true);

    }//GEN-LAST:event_imprElemActionPerformed

    private void borrElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrElemActionPerformed
     /*   EliminarDatos eli = new EliminarDatos(null, rootPaneCheckingEnabled);
        eli.setVisible(true);*/
    }//GEN-LAST:event_borrElemActionPerformed

    private void busElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busElemActionPerformed
       /* BuscarElemento bE = new BuscarElemento(null, rootPaneCheckingEnabled);
        bE.setVisible(true);*/
    }//GEN-LAST:event_busElemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrElem;
    private javax.swing.JButton busElem;
    private javax.swing.JButton editElem;
    private javax.swing.JButton imprElem;
    private javax.swing.JButton insElem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
